namespace Prevea.ConsoleTestModel.Migrations
{
    #region Using

    using System.Collections.Generic;
    using Model.Model;

    #endregion

    public static class Cnaes
    {
        public static List<Cnae> GetCnaes()
        {
            var cnaes = new List<Cnae>
            {
                new Cnae { Key = "111", CustomKey = "A111", Name = "Cultivo de cereales (excepto arroz), leguminosas y semillas oleaginosas" },
                new Cnae { Key = "112", CustomKey = "A112", Name = "Cultivo de arroz" },
                new Cnae { Key = "113", CustomKey = "A113", Name = "Cultivo de hortalizas, raíces y tubérculos" },
                new Cnae { Key = "114", CustomKey = "A114", Name = "Cultivo de caña de azúcar" },
                new Cnae { Key = "115", CustomKey = "A115", Name = "Cultivo de tabaco" },
                new Cnae { Key = "116", CustomKey = "A116", Name = "Cultivo de plantas para fibras textiles" },
                new Cnae { Key = "119", CustomKey = "A119", Name = "Otros cultivos no perennes" },
                new Cnae { Key = "121", CustomKey = "A121", Name = "Cultivo de la vid" },
                new Cnae { Key = "122", CustomKey = "A122", Name = "Cultivo de frutos tropicales y subtropicales" },
                new Cnae { Key = "123", CustomKey = "A123", Name = "Cultivo de cítricos" },
                new Cnae { Key = "124", CustomKey = "A124", Name = "Cultivo de frutos con hueso y pepitas" },
                new Cnae { Key = "125", CustomKey = "A125", Name = "Cultivo de otros árboles y arbustos frutales y frutos secos" },
                new Cnae { Key = "126", CustomKey = "A126", Name = "Cultivo de frutos oleaginosos" },
                new Cnae { Key = "127", CustomKey = "A127", Name = "Cultivo de plantas para bebidas" },
                new Cnae { Key = "128", CustomKey = "A128", Name = "Cultivo de especias, plantas aromáticas, medicinales y farmacéuticas" },
                new Cnae { Key = "129", CustomKey = "A129", Name = "Otros cultivos perennes" },
                new Cnae { Key = "130", CustomKey = "A130", Name = "Propagación de plantas" },
                new Cnae { Key = "141", CustomKey = "A141", Name = "Explotación de ganado bovino para la producción de leche" },
                new Cnae { Key = "142", CustomKey = "A142", Name = "Explotación de otro ganado bovino y búfalos" },
                new Cnae { Key = "143", CustomKey = "A143", Name = "Explotación de caballos y otros equinos" },
                new Cnae { Key = "144", CustomKey = "A144", Name = "Explotación de camellos y otros camélidos" },
                new Cnae { Key = "145", CustomKey = "A145", Name = "Explotación de ganado ovino y caprino" },
                new Cnae { Key = "146", CustomKey = "A146", Name = "Explotación de ganado porcino" },
                new Cnae { Key = "147", CustomKey = "A147", Name = "Avicultura" },
                new Cnae { Key = "149", CustomKey = "A149", Name = "Otras explotaciones de ganado" },
                new Cnae { Key = "150", CustomKey = "A150", Name = "Producción agrícola combinada con la producción ganadera" },
                new Cnae { Key = "161", CustomKey = "A161", Name = "Actividades de apoyo a la agricultura" },
                new Cnae { Key = "162", CustomKey = "A162", Name = "Actividades de apoyo a la ganadería" },
                new Cnae { Key = "163", CustomKey = "A163", Name = "Actividades de preparación posterior a la cosecha" },
                new Cnae { Key = "164", CustomKey = "A164", Name = "Tratamiento de semillas para reproducción" },
                new Cnae { Key = "170", CustomKey = "A170", Name = "Caza, captura de animales y servicios relacionados con las mismas" },
                new Cnae { Key = "210", CustomKey = "A210", Name = "Silvicultura y otras actividades forestales" },
                new Cnae { Key = "220", CustomKey = "A220", Name = "Explotación de la madera" },
                new Cnae { Key = "230", CustomKey = "A230", Name = "Recolección de productos silvestres, excepto madera" },
                new Cnae { Key = "240", CustomKey = "A240", Name = "Servicios de apoyo a la silvicultura" },
                new Cnae { Key = "311", CustomKey = "A311", Name = "Pesca marina" },
                new Cnae { Key = "312", CustomKey = "A312", Name = "Pesca en agua dulce" },
                new Cnae { Key = "321", CustomKey = "A321", Name = "Acuicultura marina" },
                new Cnae { Key = "322", CustomKey = "A322", Name = "Acuicultura en agua dulce" },
                new Cnae { Key = "510", CustomKey = "B510", Name = "Extracción de antracita y hulla" },
                new Cnae { Key = "520", CustomKey = "B520", Name = "Extracción de lignito" },
                new Cnae { Key = "610", CustomKey = "B610", Name = "Extracción de crudo de petróleo" },
                new Cnae { Key = "620", CustomKey = "B620", Name = "Extracción de gas natural" },
                new Cnae { Key = "710", CustomKey = "B710", Name = "Extracción de minerales de hierro" },
                new Cnae { Key = "721", CustomKey = "B721", Name = "Extracción de minerales de uranio y torio" },
                new Cnae { Key = "729", CustomKey = "B729", Name = "Extracción de otros minerales metálicos no férreos" },
                new Cnae { Key = "811", CustomKey = "B811", Name = "Extracción de piedra ornamental y para la construcción, piedra caliza, yeso, creta y pizarra" },
                new Cnae { Key = "812", CustomKey = "B812", Name = "Extracción de gravas y arenas; extracción de arcilla y caolín" },
                new Cnae { Key = "891", CustomKey = "B891", Name = "Extracción de minerales para productos químicos y fertilizantes" },
                new Cnae { Key = "892", CustomKey = "B892", Name = "Extracción de turba" },
                new Cnae { Key = "893", CustomKey = "B893", Name = "Extracción de sal" },
                new Cnae { Key = "899", CustomKey = "B899", Name = "Otras industrias extractivas" },
                new Cnae { Key = "910", CustomKey = "B910", Name = "Actividades de apoyo a la extracción de petróleo y gas natural" },
                new Cnae { Key = "990", CustomKey = "B990", Name = "Actividades de apoyo a otras industrias extractivas" },
                new Cnae { Key = "1011", CustomKey = "C1011", Name = "Procesado y conservación de carne" },
                new Cnae { Key = "1012", CustomKey = "C1012", Name = "Procesado y conservación de volatería" },
                new Cnae { Key = "1013", CustomKey = "C1013", Name = "Elaboración de productos cárnicos y de volatería" },
                new Cnae { Key = "1021", CustomKey = "C1021", Name = "Procesado de pescados, crustáceos y moluscos" },
                new Cnae { Key = "1022", CustomKey = "C1022", Name = "Fabricación de conservas de pescado" },
                new Cnae { Key = "1031", CustomKey = "C1031", Name = "Procesado y conservación de patatas" },
                new Cnae { Key = "1032", CustomKey = "C1032", Name = "Elaboración de zumos de frutas y hortalizas" },
                new Cnae { Key = "1039", CustomKey = "C1039", Name = "Otro procesado y conservación de frutas y hortalizas" },
                new Cnae { Key = "1042", CustomKey = "C1042", Name = "Fabricación de margarina y grasas comestibles similares" },
                new Cnae { Key = "1043", CustomKey = "C1043", Name = "Fabricación de aceite de oliva" },
                new Cnae { Key = "1044", CustomKey = "C1044", Name = "Fabricación de otros aceites y grasas" },
                new Cnae { Key = "1052", CustomKey = "C1052", Name = "Elaboración de helados" },
                new Cnae { Key = "1053", CustomKey = "C1053", Name = "Fabricación de quesos" },
                new Cnae { Key = "1054", CustomKey = "C1054", Name = "Preparación de leche y otros productos lácteos" },
                new Cnae { Key = "1061", CustomKey = "C1061", Name = "Fabricación de productos de molinería" },
                new Cnae { Key = "1062", CustomKey = "C1062", Name = "Fabricación de almidones y productos amiláceos" },
                new Cnae { Key = "1071", CustomKey = "C1071", Name = "Fabricación de pan y de productos frescos de panadería y pastelería" },
                new Cnae { Key = "1072", CustomKey = "C1072", Name = "Fabricación de galletas y productos de panadería y pastelería de larga duración" },
                new Cnae { Key = "1073", CustomKey = "C1073", Name = "Fabricación de pastas alimenticias, cuscús y productos similares" },
                new Cnae { Key = "1081", CustomKey = "C1081", Name = "Fabricación de azúcar" },
                new Cnae { Key = "1082", CustomKey = "C1082", Name = "Fabricación de cacao, chocolate y productos de confitería" },
                new Cnae { Key = "1083", CustomKey = "C1083", Name = "Elaboración de café, té e infusiones" },
                new Cnae { Key = "1084", CustomKey = "C1084", Name = "Elaboración de especias, salsas y condimentos" },
                new Cnae { Key = "1085", CustomKey = "C1085", Name = "Elaboración de platos y comidas preparados" },
                new Cnae { Key = "1086", CustomKey = "C1086", Name = "Elaboración de preparados alimenticios homogeneizados y alimentos dietéticos" },
                new Cnae { Key = "1089", CustomKey = "C1089", Name = "Elaboración de otros productos alimenticios" },
                new Cnae { Key = "1091", CustomKey = "C1091", Name = "Fabricación de productos para la alimentación de animales de granja" },
                new Cnae { Key = "1092", CustomKey = "C1092", Name = "Fabricación de productos para la alimentación de animales de compañía" },
                new Cnae { Key = "1101", CustomKey = "C1101", Name = "Destilación, rectificación y mezcla de bebidas alcohólicas" },
                new Cnae { Key = "1102", CustomKey = "C1102", Name = "Elaboración de vinos" },
                new Cnae { Key = "1103", CustomKey = "C1103", Name = "Elaboración de sidra y otras bebidas fermentadas a partir de frutas" },
                new Cnae { Key = "1104", CustomKey = "C1104", Name = "Elaboración de otras bebidas no destiladas, procedentes de la fermentación" },
                new Cnae { Key = "1105", CustomKey = "C1105", Name = "Fabricación de cerveza" },
                new Cnae { Key = "1106", CustomKey = "C1106", Name = "Fabricación de malta" },
                new Cnae { Key = "1107", CustomKey = "C1107", Name = "Fabricación de bebidas no alcohólicas; producción de aguas minerales y otras aguas embotelladas" },
                new Cnae { Key = "1200", CustomKey = "C1200", Name = "Industria del tabaco" },
                new Cnae { Key = "1310", CustomKey = "C1310", Name = "Preparación e hilado de fibras textiles" },
                new Cnae { Key = "1320", CustomKey = "C1320", Name = "Fabricación de tejidos textiles" },
                new Cnae { Key = "1330", CustomKey = "C1330", Name = "Acabado de textiles" },
                new Cnae { Key = "1391", CustomKey = "C1391", Name = "Fabricación de tejidos de punto" },
                new Cnae { Key = "1392", CustomKey = "C1392", Name = "Fabricación de artículos confeccionados con textiles, excepto prendas de vestir" },
                new Cnae { Key = "1393", CustomKey = "C1393", Name = "Fabricación de alfombras y moquetas" },
                new Cnae { Key = "1394", CustomKey = "C1394", Name = "Fabricación de cuerdas, cordeles, bramantes y redes" },
                new Cnae { Key = "1395", CustomKey = "C1395", Name = "Fabricación de telas no tejidas y artículos confeccionados con ellas, excepto prendas de vestir" },
                new Cnae { Key = "1396", CustomKey = "C1396", Name = "Fabricación de otros productos textiles de uso técnico e industrial" },
                new Cnae { Key = "1399", CustomKey = "C1399", Name = "Fabricación de otros productos textiles" },
                new Cnae { Key = "1411", CustomKey = "C1411", Name = "Confección de prendas de vestir de cuero" },
                new Cnae { Key = "1412", CustomKey = "C1412", Name = "Confección de ropa de trabajo" },
                new Cnae { Key = "1413", CustomKey = "C1413", Name = "Confección de otras prendas de vestir exteriores" },
                new Cnae { Key = "1414", CustomKey = "C1414", Name = "Confección de ropa interior" },
                new Cnae { Key = "1419", CustomKey = "C1419", Name = "Confección de otras prendas de vestir y accesorios" },
                new Cnae { Key = "1420", CustomKey = "C1420", Name = "Fabricación de artículos de peletería" },
                new Cnae { Key = "1431", CustomKey = "C1431", Name = "Confección de calcetería" },
                new Cnae { Key = "1439", CustomKey = "C1439", Name = "Confección de otras prendas de vestir de punto" },
                new Cnae { Key = "1511", CustomKey = "C1511", Name = "Preparación, curtido y acabado del cuero; preparación y teñido de pieles" },
                new Cnae { Key = "1512", CustomKey = "C1512", Name = "Fabricación de artículos de marroquinería, viaje y de guarnicionería y talabartería" },
                new Cnae { Key = "1520", CustomKey = "C1520", Name = "Fabricación de calzado" },
                new Cnae { Key = "1610", CustomKey = "C1610", Name = "Aserrado y cepillado de la madera" },
                new Cnae { Key = "1621", CustomKey = "C1621", Name = "Fabricación de chapas y tableros de madera" },
                new Cnae { Key = "1622", CustomKey = "C1622", Name = "Fabricación de suelos de madera ensamblados" },
                new Cnae { Key = "1623", CustomKey = "C1623", Name = "Fabricación de otras estructuras de madera y piezas de carpintería y ebanistería para la construcción" },
                new Cnae { Key = "1624", CustomKey = "C1624", Name = "Fabricación de envases y embalajes de madera" },
                new Cnae { Key = "1629", CustomKey = "C1629", Name = "Fabricación de otros productos de madera; artículos de corcho, cestería y espartería" },
                new Cnae { Key = "1711", CustomKey = "C1711", Name = "Fabricación de pasta papelera" },
                new Cnae { Key = "1712", CustomKey = "C1712", Name = "Fabricación de papel y cartón" },
                new Cnae { Key = "1721", CustomKey = "C1721", Name = "Fabricación de papel y cartón ondulados; fabricación de envases y embalajes de papel y cartón" },
                new Cnae { Key = "1722", CustomKey = "C1722", Name = "Fabricación de artículos de papel y cartón para uso doméstico, sanitario e higiénico" },
                new Cnae { Key = "1723", CustomKey = "C1723", Name = "Fabricación de artículos de papelería" },
                new Cnae { Key = "1724", CustomKey = "C1724", Name = "Fabricación de papeles pintados" },
                new Cnae { Key = "1729", CustomKey = "C1729", Name = "Fabricación de otros artículos de papel y cartón" },
                new Cnae { Key = "1811", CustomKey = "C1811", Name = "Artes gráficas y servicios relacionados con las mismas" },
                new Cnae { Key = "1812", CustomKey = "C1812", Name = "Otras actividades de impresión y artes gráficas" },
                new Cnae { Key = "1813", CustomKey = "C1813", Name = "Servicios de preimpresión y preparación de soportes" },
                new Cnae { Key = "1814", CustomKey = "C1814", Name = "Encuadernación y servicios relacionados con la misma" },
                new Cnae { Key = "1820", CustomKey = "C1820", Name = "Reproducción de soportes grabados" },
                new Cnae { Key = "1910", CustomKey = "C1910", Name = "Coquerías" },
                new Cnae { Key = "1920", CustomKey = "C1920", Name = "Refino de petróleo" },
                new Cnae { Key = "2011", CustomKey = "C2011", Name = "Fabricación de gases industriales" },
                new Cnae { Key = "2012", CustomKey = "C2012", Name = "Fabricación de colorantes y pigmentos" },
                new Cnae { Key = "2013", CustomKey = "C2013", Name = "Fabricación de otros productos básicos de química inorgánica" },
                new Cnae { Key = "2014", CustomKey = "C2014", Name = "Fabricación de otros productos básicos de química orgánica" },
                new Cnae { Key = "2015", CustomKey = "C2015", Name = "Fabricación de fertilizantes y compuestos nitrogenados" },
                new Cnae { Key = "2016", CustomKey = "C2016", Name = "Fabricación de plásticos en formas primarias" },
                new Cnae { Key = "2017", CustomKey = "C2017", Name = "Fabricación de caucho sintético en formas primarias" },
                new Cnae { Key = "2020", CustomKey = "C2020", Name = "Fabricación de pesticidas y otros productos agroquímicos" },
                new Cnae { Key = "2030", CustomKey = "C2030", Name = "Fabricación de pinturas, barnices y revestimientos similares; tintas de imprenta y masillas" },
                new Cnae { Key = "2041", CustomKey = "C2041", Name = "Fabricación de jabones, detergentes y otros artículos de limpieza y abrillantamiento" },
                new Cnae { Key = "2042", CustomKey = "C2042", Name = "Fabricación de perfumes y cosméticos" },
                new Cnae { Key = "2051", CustomKey = "C2051", Name = "Fabricación de explosivos" },
                new Cnae { Key = "2052", CustomKey = "C2052", Name = "Fabricación de colas" },
                new Cnae { Key = "2053", CustomKey = "C2053", Name = "Fabricación de aceites esenciales" },
                new Cnae { Key = "2059", CustomKey = "C2059", Name = "Fabricación de otros productos químicos" },
                new Cnae { Key = "2060", CustomKey = "C2060", Name = "Fabricación de fibras artificiales y sintéticas" },
                new Cnae { Key = "2110", CustomKey = "C2110", Name = "Fabricación de productos farmacéuticos de base" },
                new Cnae { Key = "2120", CustomKey = "C2120", Name = "Fabricación de especialidades farmacéuticas" },
                new Cnae { Key = "2211", CustomKey = "C2211", Name = "Fabricación de neumáticos y cámaras de caucho; reconstrucción y recauchutado de neumáticos" },
                new Cnae { Key = "2219", CustomKey = "C2219", Name = "Fabricación de otros productos de caucho" },
                new Cnae { Key = "2221", CustomKey = "C2221", Name = "Fabricación de placas, hojas, tubos y perfiles de plástico" },
                new Cnae { Key = "2222", CustomKey = "C2222", Name = "Fabricación de envases y embalajes de plástico" },
                new Cnae { Key = "2223", CustomKey = "C2223", Name = "Fabricación de productos de plástico para la construcción" },
                new Cnae { Key = "2229", CustomKey = "C2229", Name = "Fabricación de otros productos de plástico" },
                new Cnae { Key = "2311", CustomKey = "C2311", Name = "Fabricación de vidrio plano" },
                new Cnae { Key = "2312", CustomKey = "C2312", Name = "Manipulado y transformación de vidrio plano" },
                new Cnae { Key = "2313", CustomKey = "C2313", Name = "Fabricación de vidrio hueco" },
                new Cnae { Key = "2314", CustomKey = "C2314", Name = "Fabricación de fibra de vidrio" },
                new Cnae { Key = "2319", CustomKey = "C2319", Name = "Fabricación y manipulado de otro vidrio, incluido el vidrio técnico" },
                new Cnae { Key = "2320", CustomKey = "C2320", Name = "Fabricación de productos cerámicos refractarios" },
                new Cnae { Key = "2331", CustomKey = "C2331", Name = "Fabricación de azulejos y baldosas de cerámica" },
                new Cnae { Key = "2332", CustomKey = "C2332", Name = "Fabricación de ladrillos, tejas y productos de tierras cocidas para la construcción" },
                new Cnae { Key = "2341", CustomKey = "C2341", Name = "Fabricación de artículos cerámicos de uso doméstico y ornamental" },
                new Cnae { Key = "2342", CustomKey = "C2342", Name = "Fabricación de aparatos sanitarios cerámicos" },
                new Cnae { Key = "2343", CustomKey = "C2343", Name = "Fabricación de aisladores y piezas aislantes de material cerámico" },
                new Cnae { Key = "2344", CustomKey = "C2344", Name = "Fabricación de otros productos cerámicos de uso técnico" },
                new Cnae { Key = "2349", CustomKey = "C2349", Name = "Fabricación de otros productos cerámicos" },
                new Cnae { Key = "2351", CustomKey = "C2351", Name = "Fabricación de cemento" },
                new Cnae { Key = "2352", CustomKey = "C2352", Name = "Fabricación de cal y yeso" },
                new Cnae { Key = "2361", CustomKey = "C2361", Name = "Fabricación de elementos de hormigón para la construcción" },
                new Cnae { Key = "2362", CustomKey = "C2362", Name = "Fabricación de elementos de yeso para la construcción" },
                new Cnae { Key = "2363", CustomKey = "C2363", Name = "Fabricación de hormigón fresco" },
                new Cnae { Key = "2364", CustomKey = "C2364", Name = "Fabricación de mortero" },
                new Cnae { Key = "2365", CustomKey = "C2365", Name = "Fabricación de fibrocemento" },
                new Cnae { Key = "2369", CustomKey = "C2369", Name = "Fabricación de otros productos de hormigón, yeso y cemento" },
                new Cnae { Key = "2370", CustomKey = "C2370", Name = "Corte, tallado y acabado de la piedra" },
                new Cnae { Key = "2391", CustomKey = "C2391", Name = "Fabricación de productos abrasivos" },
                new Cnae { Key = "2399", CustomKey = "C2399", Name = "Fabricación de otros productos minerales no metálicos" },
                new Cnae { Key = "2410", CustomKey = "C2410", Name = "Fabricación de productos básicos de hierro, acero y ferroaleaciones" },
                new Cnae { Key = "2420", CustomKey = "C2420", Name = "Fabricación de tubos, tuberías, perfiles huecos y sus accesorios, de acero" },
                new Cnae { Key = "2431", CustomKey = "C2431", Name = "Estirado en frío" },
                new Cnae { Key = "2432", CustomKey = "C2432", Name = "Laminación en frío" },
                new Cnae { Key = "2433", CustomKey = "C2433", Name = "Producción de perfiles en frío por conformación con plegado" },
                new Cnae { Key = "2434", CustomKey = "C2434", Name = "Trefilado en frío" },
                new Cnae { Key = "2441", CustomKey = "C2441", Name = "Producción de metales preciosos" },
                new Cnae { Key = "2442", CustomKey = "C2442", Name = "Producción de aluminio" },
                new Cnae { Key = "2443", CustomKey = "C2443", Name = "Producción de plomo, zinc y estaño" },
                new Cnae { Key = "2444", CustomKey = "C2444", Name = "Producción de cobre" },
                new Cnae { Key = "2445", CustomKey = "C2445", Name = "Producción de otros metales no férreos" },
                new Cnae { Key = "2446", CustomKey = "C2446", Name = "Procesamiento de combustibles nucleares" },
                new Cnae { Key = "2451", CustomKey = "C2451", Name = "Fundición de hierro" },
                new Cnae { Key = "2452", CustomKey = "C2452", Name = "Fundición de acero" },
                new Cnae { Key = "2453", CustomKey = "C2453", Name = "Fundición de metales ligeros" },
                new Cnae { Key = "2454", CustomKey = "C2454", Name = "Fundición de otros metales no férreos" },
                new Cnae { Key = "2511", CustomKey = "C2511", Name = "Fabricación de estructuras metálicas y sus componentes" },
                new Cnae { Key = "2512", CustomKey = "C2512", Name = "Fabricación de carpintería metálica" },
                new Cnae { Key = "2521", CustomKey = "C2521", Name = "Fabricación de radiadores y calderas para calefacción central" },
                new Cnae { Key = "2529", CustomKey = "C2529", Name = "Fabricación de otras cisternas, grandes depósitos y contenedores de metal" },
                new Cnae { Key = "2530", CustomKey = "C2530", Name = "Fabricación de generadores de vapor, excepto calderas de calefacción central" },
                new Cnae { Key = "2540", CustomKey = "C2540", Name = "Fabricación de armas y municiones" },
                new Cnae { Key = "2550", CustomKey = "C2550", Name = "Forja, estampación y embutición de metales; metalurgia de polvos" },
                new Cnae { Key = "2561", CustomKey = "C2561", Name = "Tratamiento y revestimiento de metales" },
                new Cnae { Key = "2562", CustomKey = "C2562", Name = "Ingeniería mecánica por cuenta de terceros" },
                new Cnae { Key = "2571", CustomKey = "C2571", Name = "Fabricación de artículos de cuchillería y cubertería" },
                new Cnae { Key = "2572", CustomKey = "C2572", Name = "Fabricación de cerraduras y herrajes" },
                new Cnae { Key = "2573", CustomKey = "C2573", Name = "Fabricación de herramientas" },
                new Cnae { Key = "2591", CustomKey = "C2591", Name = "Fabricación de bidones y toneles de hierro o acero" },
                new Cnae { Key = "2592", CustomKey = "C2592", Name = "Fabricación de envases y embalajes metálicos ligeros" },
                new Cnae { Key = "2593", CustomKey = "C2593", Name = "Fabricación de productos de alambre, cadenas y muelles" },
                new Cnae { Key = "2594", CustomKey = "C2594", Name = "Fabricación de pernos y productos de tornillería" },
                new Cnae { Key = "2599", CustomKey = "C2599", Name = "Fabricación de otros productos metálicos" },
                new Cnae { Key = "2611", CustomKey = "C2611", Name = "Fabricación de componentes electrónicos" },
                new Cnae { Key = "2612", CustomKey = "C2612", Name = "Fabricación de circuitos impresos ensamblados" },
                new Cnae { Key = "2620", CustomKey = "C2620", Name = "Fabricación de ordenadores y equipos periféricos" },
                new Cnae { Key = "2630", CustomKey = "C2630", Name = "Fabricación de equipos de telecomunicaciones" },
                new Cnae { Key = "2640", CustomKey = "C2640", Name = "Fabricación de productos electrónicos de consumo" },
                new Cnae { Key = "2651", CustomKey = "C2651", Name = "Fabricación de instrumentos y aparatos de medida, verificación y navegación" },
                new Cnae { Key = "2652", CustomKey = "C2652", Name = "Fabricación de relojes" },
                new Cnae { Key = "2660", CustomKey = "C2660", Name = "Fabricación de equipos de radiación, electromédicos y electroterapéuticos" },
                new Cnae { Key = "2670", CustomKey = "C2670", Name = "Fabricación de instrumentos de óptica y equipo fotográfico" },
                new Cnae { Key = "2680", CustomKey = "C2680", Name = "Fabricación de soportes magnéticos y ópticos" },
                new Cnae { Key = "2711", CustomKey = "C2711", Name = "Fabricación de motores, generadores y transformadores eléctricos" },
                new Cnae { Key = "2712", CustomKey = "C2712", Name = "Fabricación de aparatos de distribución y control eléctrico" },
                new Cnae { Key = "2720", CustomKey = "C2720", Name = "Fabricación de pilas y acumuladores eléctricos" },
                new Cnae { Key = "2731", CustomKey = "C2731", Name = "Fabricación de cables de fibra óptica" },
                new Cnae { Key = "2732", CustomKey = "C2732", Name = "Fabricación de otros hilos y cables electrónicos y eléctricos" },
                new Cnae { Key = "2733", CustomKey = "C2733", Name = "Fabricación de dispositivos de cableado" },
                new Cnae { Key = "2740", CustomKey = "C2740", Name = "Fabricación de lámparas y aparatos eléctricos de iluminación" },
                new Cnae { Key = "2751", CustomKey = "C2751", Name = "Fabricación de electrodomésticos" },
                new Cnae { Key = "2752", CustomKey = "C2752", Name = "Fabricación de aparatos domésticos no eléctricos" },
                new Cnae { Key = "2790", CustomKey = "C2790", Name = "Fabricación de otro material y equipo eléctrico" },
                new Cnae { Key = "2811", CustomKey = "C2811", Name = "Fabricación de motores y turbinas, excepto los destinados a aeronaves, vehículos automóviles y ciclomotores" },
                new Cnae { Key = "2812", CustomKey = "C2812", Name = "Fabricación de equipos de transmisión hidráulica y neumática" },
                new Cnae { Key = "2813", CustomKey = "C2813", Name = "Fabricación de otras bombas y compresores" },
                new Cnae { Key = "2814", CustomKey = "C2814", Name = "Fabricación de otra grifería y válvulas" },
                new Cnae { Key = "2815", CustomKey = "C2815", Name = "Fabricación de cojinetes, engranajes y órganos mecánicos de transmisión" },
                new Cnae { Key = "2821", CustomKey = "C2821", Name = "Fabricación de hornos y quemadores" },
                new Cnae { Key = "2822", CustomKey = "C2822", Name = "Fabricación de maquinaria de elevación y manipulación" },
                new Cnae { Key = "2823", CustomKey = "C2823", Name = "Fabricación de máquinas y equipos de oficina, excepto equipos informáticos" },
                new Cnae { Key = "2824", CustomKey = "C2824", Name = "Fabricación de herramientas eléctricas manuales" },
                new Cnae { Key = "2825", CustomKey = "C2825", Name = "Fabricación de maquinaria de ventilación y refrigeración no doméstica" },
                new Cnae { Key = "2829", CustomKey = "C2829", Name = "Fabricación de otra maquinaria de uso general" },
                new Cnae { Key = "2830", CustomKey = "C2830", Name = "Fabricación de maquinaria agraria y forestal" },
                new Cnae { Key = "2841", CustomKey = "C2841", Name = "Fabricación de máquinas herramienta para trabajar el metal" },
                new Cnae { Key = "2849", CustomKey = "C2849", Name = "Fabricación de otras máquinas herramienta" },
                new Cnae { Key = "2891", CustomKey = "C2891", Name = "Fabricación de maquinaria para la industria metalúrgica" },
                new Cnae { Key = "2892", CustomKey = "C2892", Name = "Fabricación de maquinaria para las industrias extractivas y de la construcción" },
                new Cnae { Key = "2893", CustomKey = "C2893", Name = "Fabricación de maquinaria para la industria de la alimentación, bebidas y tabaco" },
                new Cnae { Key = "2894", CustomKey = "C2894", Name = "Fabricación de maquinaria para las industrias textil, de la confección y del cuero" },
                new Cnae { Key = "2895", CustomKey = "C2895", Name = "Fabricación de maquinaria para la industria del papel y del cartón" },
                new Cnae { Key = "2896", CustomKey = "C2896", Name = "Fabricación de maquinaria para la industria del plástico y el caucho" },
                new Cnae { Key = "2899", CustomKey = "C2899", Name = "Fabricación de otra maquinaria para usos específicos" },
                new Cnae { Key = "2910", CustomKey = "C2910", Name = "Fabricación de vehículos de motor" },
                new Cnae { Key = "2920", CustomKey = "C2920", Name = "Fabricación de carrocerías para vehículos de motor; fabricación de remolques y semirremolques" },
                new Cnae { Key = "2931", CustomKey = "C2931", Name = "Fabricación de equipos eléctricos y electrónicos para vehículos de motor" },
                new Cnae { Key = "2932", CustomKey = "C2932", Name = "Fabricación de otros componentes, piezas y accesorios para vehículos de motor" },
                new Cnae { Key = "3011", CustomKey = "C3011", Name = "Construcción de barcos y estructuras flotantes" },
                new Cnae { Key = "3012", CustomKey = "C3012", Name = "Construcción de embarcaciones de recreo y deporte" },
                new Cnae { Key = "3020", CustomKey = "C3020", Name = "Fabricación de locomotoras y material ferroviario" },
                new Cnae { Key = "3030", CustomKey = "C3030", Name = "Construcción aeronáutica y espacial y su maquinaria" },
                new Cnae { Key = "3040", CustomKey = "C3040", Name = "Fabricación de vehículos militares de combate" },
                new Cnae { Key = "3091", CustomKey = "C3091", Name = "Fabricación de motocicletas" },
                new Cnae { Key = "3092", CustomKey = "C3092", Name = "Fabricación de bicicletas y de vehículos para personas con discapacidad" },
                new Cnae { Key = "3099", CustomKey = "C3099", Name = "Fabricación de otro material de transporte" },
                new Cnae { Key = "3101", CustomKey = "C3101", Name = "Fabricación de muebles de oficina y de establecimientos comerciales" },
                new Cnae { Key = "3102", CustomKey = "C3102", Name = "Fabricación de muebles de cocina" },
                new Cnae { Key = "3103", CustomKey = "C3103", Name = "Fabricación de colchones" },
                new Cnae { Key = "3109", CustomKey = "C3109", Name = "Fabricación de otros muebles" },
                new Cnae { Key = "3211", CustomKey = "C3211", Name = "Fabricación de monedas" },
                new Cnae { Key = "3212", CustomKey = "C3212", Name = "Fabricación de artículos de joyería y artículos similares" },
                new Cnae { Key = "3213", CustomKey = "C3213", Name = "Fabricación de artículos de bisutería y artículos similares" },
                new Cnae { Key = "3220", CustomKey = "C3220", Name = "Fabricación de instrumentos musicales" },
                new Cnae { Key = "3230", CustomKey = "C3230", Name = "Fabricación de artículos de deporte" },
                new Cnae { Key = "3240", CustomKey = "C3240", Name = "Fabricación de juegos y juguetes" },
                new Cnae { Key = "3250", CustomKey = "C3250", Name = "Fabricación de instrumentos y suministros médicos y odontológicos" },
                new Cnae { Key = "3291", CustomKey = "C3291", Name = "Fabricación de escobas, brochas y cepillos" },
                new Cnae { Key = "3299", CustomKey = "C3299", Name = "Otras industrias manufactureras" },
                new Cnae { Key = "3311", CustomKey = "C3311", Name = "Reparación de productos metálicos" },
                new Cnae { Key = "3312", CustomKey = "C3312", Name = "Reparación de maquinaria" },
                new Cnae { Key = "3313", CustomKey = "C3313", Name = "Reparación de equipos electrónicos y ópticos" },
                new Cnae { Key = "3314", CustomKey = "C3314", Name = "Reparación de equipos eléctricos" },
                new Cnae { Key = "3315", CustomKey = "C3315", Name = "Reparación y mantenimiento naval" },
                new Cnae { Key = "3316", CustomKey = "C3316", Name = "Reparación y mantenimiento aeronáutico y espacial" },
                new Cnae { Key = "3317", CustomKey = "C3317", Name = "Reparación y mantenimiento de otro material de transporte" },
                new Cnae { Key = "3319", CustomKey = "C3319", Name = "Reparación de otros equipos" },
                new Cnae { Key = "3320", CustomKey = "C3320", Name = "Instalación de máquinas y equipos industriales" },
                new Cnae { Key = "3512", CustomKey = "D3512", Name = "Transporte de energía eléctrica" },
                new Cnae { Key = "3513", CustomKey = "D3513", Name = "Distribución de energía eléctrica" },
                new Cnae { Key = "3514", CustomKey = "D3514", Name = "Comercio de energía eléctrica" },
                new Cnae { Key = "3515", CustomKey = "D3515", Name = "Producción de energía hidroeléctrica" },
                new Cnae { Key = "3516", CustomKey = "D3516", Name = "Producción de energía eléctrica de origen térmico convencional" },
                new Cnae { Key = "3517", CustomKey = "D3517", Name = "Producción de energía eléctrica de origen nuclear" },
                new Cnae { Key = "3518", CustomKey = "D3518", Name = "Producción de energía eléctrica de origen eólico" },
                new Cnae { Key = "3519", CustomKey = "D3519", Name = "Producción de energía eléctrica de otros tipos" },
                new Cnae { Key = "3521", CustomKey = "D3521", Name = "Producción de gas" },
                new Cnae { Key = "3522", CustomKey = "D3522", Name = "Distribución por tubería de combustibles gaseosos" },
                new Cnae { Key = "3523", CustomKey = "D3523", Name = "Comercio de gas por tubería" },
                new Cnae { Key = "3530", CustomKey = "D3530", Name = "Suministro de vapor y aire acondicionado" },
                new Cnae { Key = "3600", CustomKey = "E3600", Name = "Captación, depuración y distribución de agua" },
                new Cnae { Key = "3700", CustomKey = "E3700", Name = "Recogida y tratamiento de aguas residuales" },
                new Cnae { Key = "3811", CustomKey = "E3811", Name = "Recogida de residuos no peligrosos" },
                new Cnae { Key = "3812", CustomKey = "E3812", Name = "Recogida de residuos peligrosos" },
                new Cnae { Key = "3821", CustomKey = "E3821", Name = "Tratamiento y eliminación de residuos no peligrosos" },
                new Cnae { Key = "3822", CustomKey = "E3822", Name = "Tratamiento y eliminación de residuos peligrosos" },
                new Cnae { Key = "3831", CustomKey = "E3831", Name = "Separación y clasificación de materiales" },
                new Cnae { Key = "3832", CustomKey = "E3832", Name = "Valorización de materiales ya clasificados" },
                new Cnae { Key = "3900", CustomKey = "E3900", Name = "Actividades de descontaminación y otros servicios de gestión de residuos" },
                new Cnae { Key = "4110", CustomKey = "F4110", Name = "Promoción inmobiliaria" },
                new Cnae { Key = "4121", CustomKey = "F4121", Name = "Construcción de edificios residenciales" },
                new Cnae { Key = "4122", CustomKey = "F4122", Name = "Construcción de edificios no residenciales" },
                new Cnae { Key = "4211", CustomKey = "F4211", Name = "Construcción de carreteras y autopistas" },
                new Cnae { Key = "4212", CustomKey = "F4212", Name = "Construcción de vías férreas de superficie y subterráneas" },
                new Cnae { Key = "4213", CustomKey = "F4213", Name = "Construcción de puentes y túneles" },
                new Cnae { Key = "4221", CustomKey = "F4221", Name = "Construcción de redes para fluidos" },
                new Cnae { Key = "4222", CustomKey = "F4222", Name = "Construcción de redes eléctricas y de telecomunicaciones" },
                new Cnae { Key = "4291", CustomKey = "F4291", Name = "Obras hidráulicas" },
                new Cnae { Key = "4299", CustomKey = "F4299", Name = "Construcción de otros proyectos de ingeniería civil" },
                new Cnae { Key = "4311", CustomKey = "F4311", Name = "Demolición" },
                new Cnae { Key = "4312", CustomKey = "F4312", Name = "Preparación de terrenos" },
                new Cnae { Key = "4313", CustomKey = "F4313", Name = "Perforaciones y sondeos" },
                new Cnae { Key = "4321", CustomKey = "F4321", Name = "Instalaciones eléctricas" },
                new Cnae { Key = "4322", CustomKey = "F4322", Name = "Fontanería, instalaciones de sistemas de calefacción y aire acondicionado" },
                new Cnae { Key = "4329", CustomKey = "F4329", Name = "Otras instalaciones en obras de construcción" },
                new Cnae { Key = "4331", CustomKey = "F4331", Name = "Revocamiento" },
                new Cnae { Key = "4332", CustomKey = "F4332", Name = "Instalación de carpintería" },
                new Cnae { Key = "4333", CustomKey = "F4333", Name = "Revestimiento de suelos y paredes" },
                new Cnae { Key = "4334", CustomKey = "F4334", Name = "Pintura y acristalamiento" },
                new Cnae { Key = "4339", CustomKey = "F4339", Name = "Otro acabado de edificios" },
                new Cnae { Key = "4391", CustomKey = "F4391", Name = "Construcción de cubiertas" },
                new Cnae { Key = "4399", CustomKey = "F4399", Name = "Otras actividades de construcción especializada" },
                new Cnae { Key = "4511", CustomKey = "G4511", Name = "Venta de automóviles y vehículos de motor ligeros" },
                new Cnae { Key = "4519", CustomKey = "G4519", Name = "Venta de otros vehículos de motor" },
                new Cnae { Key = "4520", CustomKey = "G4520", Name = "Mantenimiento y reparación de vehículos de motor" },
                new Cnae { Key = "4531", CustomKey = "G4531", Name = "Comercio al por mayor de repuestos y accesorios de vehículos de motor" },
                new Cnae { Key = "4532", CustomKey = "G4532", Name = "Comercio al por menor de repuestos y accesorios de vehículos de motor" },
                new Cnae { Key = "4540", CustomKey = "G4540", Name = "Venta, mantenimiento y reparación de motocicletas y de sus repuestos y accesorios" },
                new Cnae { Key = "4611", CustomKey = "G4611", Name = "Intermediarios del comercio de materias primas agrarias, animales vivos, materias primas textiles y productos semielaborados" },
                new Cnae { Key = "4612", CustomKey = "G4612", Name = "Intermediarios del comercio de combustibles, minerales, metales y productos químicos industriales" },
                new Cnae { Key = "4613", CustomKey = "G4613", Name = "Intermediarios del comercio de la madera y materiales de construcción" },
                new Cnae { Key = "4614", CustomKey = "G4614", Name = "Intermediarios del comercio de maquinaria, equipo industrial, embarcaciones y aeronaves" },
                new Cnae { Key = "4615", CustomKey = "G4615", Name = "Intermediarios del comercio de muebles, artículos para el hogar y ferretería" },
                new Cnae { Key = "4616", CustomKey = "G4616", Name = "Intermediarios del comercio de textiles, prendas de vestir, peletería, calzado y artículos de cuero" },
                new Cnae { Key = "4617", CustomKey = "G4617", Name = "Intermediarios del comercio de productos alimenticios, bebidas y tabaco" },
                new Cnae { Key = "4618", CustomKey = "G4618", Name = "Intermediarios del comercio especializados en la venta de otros productos específicos" },
                new Cnae { Key = "4619", CustomKey = "G4619", Name = "Intermediarios del comercio de productos diversos" },
                new Cnae { Key = "4621", CustomKey = "G4621", Name = "Comercio al por mayor de cereales, tabaco en rama, simientes y alimentos para animales" },
                new Cnae { Key = "4622", CustomKey = "G4622", Name = "Comercio al por mayor de flores y plantas" },
                new Cnae { Key = "4623", CustomKey = "G4623", Name = "Comercio al por mayor de animales vivos" },
                new Cnae { Key = "4624", CustomKey = "G4624", Name = "Comercio al por mayor de cueros y pieles" },
                new Cnae { Key = "4631", CustomKey = "G4631", Name = "Comercio al por mayor de frutas y hortalizas" },
                new Cnae { Key = "4632", CustomKey = "G4632", Name = "Comercio al por mayor de carne y productos cárnicos" },
                new Cnae { Key = "4633", CustomKey = "G4633", Name = "Comercio al por mayor de productos lácteos, huevos, aceites y grasas comestibles" },
                new Cnae { Key = "4634", CustomKey = "G4634", Name = "Comercio al por mayor de bebidas" },
                new Cnae { Key = "4635", CustomKey = "G4635", Name = "Comercio al por mayor de productos del tabaco" },
                new Cnae { Key = "4636", CustomKey = "G4636", Name = "Comercio al por mayor de azúcar, chocolate y confitería" },
                new Cnae { Key = "4637", CustomKey = "G4637", Name = "Comercio al por mayor de café, té, cacao y especias" },
                new Cnae { Key = "4638", CustomKey = "G4638", Name = "Comercio al por mayor de pescados y mariscos y otros productos alimenticios" },
                new Cnae { Key = "4639", CustomKey = "G4639", Name = "Comercio al por mayor, no especializado, de productos alimenticios, bebidas y tabaco" },
                new Cnae { Key = "4641", CustomKey = "G4641", Name = "Comercio al por mayor de textiles" },
                new Cnae { Key = "4642", CustomKey = "G4642", Name = "Comercio al por mayor de prendas de vestir y calzado" },
                new Cnae { Key = "4643", CustomKey = "G4643", Name = "Comercio al por mayor de aparatos electrodomésticos" },
                new Cnae { Key = "4644", CustomKey = "G4644", Name = "Comercio al por mayor de porcelana, cristalería y artículos de limpieza" },
                new Cnae { Key = "4645", CustomKey = "G4645", Name = "Comercio al por mayor de productos perfumería y cosmética" },
                new Cnae { Key = "4646", CustomKey = "G4646", Name = "Comercio al por mayor de productos farmacéuticos" },
                new Cnae { Key = "4647", CustomKey = "G4647", Name = "Comercio al por mayor de muebles, alfombras y aparatos de iluminación" },
                new Cnae { Key = "4648", CustomKey = "G4648", Name = "Comercio al por mayor de artículos de relojería y joyería" },
                new Cnae { Key = "4649", CustomKey = "G4649", Name = "Comercio al por mayor de otros artículos de uso doméstico" },
                new Cnae { Key = "4651", CustomKey = "G4651", Name = "Comercio al por mayor de ordenadores, equipos periféricos y programas informáticos" },
                new Cnae { Key = "4652", CustomKey = "G4652", Name = "Comercio al por mayor de equipos electrónicos y de telecomunicaciones y sus componentes" },
                new Cnae { Key = "4661", CustomKey = "G4661", Name = "Comercio al por mayor de maquinaria, equipos y suministros agrícolas" },
                new Cnae { Key = "4662", CustomKey = "G4662", Name = "Comercio al por mayor de máquinas herramienta" },
                new Cnae { Key = "4663", CustomKey = "G4663", Name = "Comercio al por mayor de maquinaria para la minería, la construcción y la ingeniería civil" },
                new Cnae { Key = "4664", CustomKey = "G4664", Name = "Comercio al por mayor de maquinaria para la industria textil y de máquinas de coser y tricotar" },
                new Cnae { Key = "4665", CustomKey = "G4665", Name = "Comercio al por mayor de muebles de oficina" },
                new Cnae { Key = "4666", CustomKey = "G4666", Name = "Comercio al por mayor de otra maquinaria y equipo de oficina" },
                new Cnae { Key = "4669", CustomKey = "G4669", Name = "Comercio al por mayor de otra maquinaria y equipo" },
                new Cnae { Key = "4671", CustomKey = "G4671", Name = "Comercio al por mayor de combustibles sólidos, líquidos y gaseosos, y productos similares" },
                new Cnae { Key = "4672", CustomKey = "G4672", Name = "Comercio al por mayor de metales y minerales metálicos" },
                new Cnae { Key = "4673", CustomKey = "G4673", Name = "Comercio al por mayor de madera, materiales de construcción y aparatos sanitarios" },
                new Cnae { Key = "4674", CustomKey = "G4674", Name = "Comercio al por mayor de ferretería, fontanería y calefacción" },
                new Cnae { Key = "4675", CustomKey = "G4675", Name = "Comercio al por mayor de productos químicos" },
                new Cnae { Key = "4676", CustomKey = "G4676", Name = "Comercio al por mayor de otros productos semielaborados" },
                new Cnae { Key = "4677", CustomKey = "G4677", Name = "Comercio al por mayor de chatarra y productos de desecho" },
                new Cnae { Key = "4690", CustomKey = "G4690", Name = "Comercio al por mayor no especializado" },
                new Cnae { Key = "4711", CustomKey = "G4711", Name = "Comercio al por menor en establecimientos no especializados, con predominio en productos alimenticios, bebidas y tabaco" },
                new Cnae { Key = "4719", CustomKey = "G4719", Name = "Otro comercio al por menor en establecimientos no especializados" },
                new Cnae { Key = "4721", CustomKey = "G4721", Name = "Comercio al por menor de frutas y hortalizas en establecimientos especializados" },
                new Cnae { Key = "4722", CustomKey = "G4722", Name = "Comercio al por menor de carne y productos cárnicos en establecimientos especializados" },
                new Cnae { Key = "4723", CustomKey = "G4723", Name = "Comercio al por menor de pescados y mariscos en establecimientos especializados" },
                new Cnae { Key = "4724", CustomKey = "G4724", Name = "Comercio al por menor de pan y productos de panadería, confitería y pastelería en establecimientos especializados" },
                new Cnae { Key = "4725", CustomKey = "G4725", Name = "Comercio al por menor de bebidas en establecimientos especializados" },
                new Cnae { Key = "4726", CustomKey = "G4726", Name = "Comercio al por menor de productos de tabaco en establecimientos especializados" },
                new Cnae { Key = "4729", CustomKey = "G4729", Name = "Otro comercio al por menor de productos alimenticios en establecimientos especializados" },
                new Cnae { Key = "4730", CustomKey = "G4730", Name = "Comercio al por menor de combustible para la automoción en establecimientos especializados" },
                new Cnae { Key = "4741", CustomKey = "G4741", Name = "Comercio al por menor de ordenadores, equipos periféricos y programas informáticos en establecimientos especializados" },
                new Cnae { Key = "4742", CustomKey = "G4742", Name = "Comercio al por menor de equipos de telecomunicaciones en establecimientos especializados" },
                new Cnae { Key = "4743", CustomKey = "G4743", Name = "Comercio al por menor de equipos de audio y vídeo en establecimientos especializados" },
                new Cnae { Key = "4751", CustomKey = "G4751", Name = "Comercio al por menor de textiles en establecimientos especializados" },
                new Cnae { Key = "4752", CustomKey = "G4752", Name = "Comercio al por menor de ferretería, pintura y vidrio en establecimientos especializados" },
                new Cnae { Key = "4753", CustomKey = "G4753", Name = "Comercio al por menor de alfombras, moquetas y revestimientos de paredes y suelos en establecimientos especializados" },
                new Cnae { Key = "4754", CustomKey = "G4754", Name = "Comercio al por menor de aparatos electrodomésticos en establecimientos especializados" },
                new Cnae { Key = "4759", CustomKey = "G4759", Name = "Comercio al por menor de muebles, aparatos de iluminación y otros artículos de uso doméstico en establecimientos especializados" },
                new Cnae { Key = "4761", CustomKey = "G4761", Name = "Comercio al por menor de libros en establecimientos especializados" },
                new Cnae { Key = "4762", CustomKey = "G4762", Name = "Comercio al por menor de periódicos y artículos de papelería en establecimientos especializados" },
                new Cnae { Key = "4763", CustomKey = "G4763", Name = "Comercio al por menor de grabaciones de música y vídeo en establecimientos especializados" },
                new Cnae { Key = "4764", CustomKey = "G4764", Name = "Comercio al por menor de artículos deportivos en establecimientos especializados" },
                new Cnae { Key = "4765", CustomKey = "G4765", Name = "Comercio al por menor de juegos y juguetes en establecimientos especializados" },
                new Cnae { Key = "4771", CustomKey = "G4771", Name = "Comercio al por menor de prendas de vestir en establecimientos especializados" },
                new Cnae { Key = "4772", CustomKey = "G4772", Name = "Comercio al por menor de calzado y artículos de cuero en establecimientos especializados" },
                new Cnae { Key = "4773", CustomKey = "G4773", Name = "Comercio al por menor de productos farmacéuticos en establecimientos especializados" },
                new Cnae { Key = "4774", CustomKey = "G4774", Name = "Comercio al por menor de artículos médicos y ortopédicos en establecimientos especializados" },
                new Cnae { Key = "4775", CustomKey = "G4775", Name = "Comercio al por menor de productos cosméticos e higiénicos en establecimientos especializados" },
                new Cnae { Key = "4776", CustomKey = "G4776", Name = "Comercio al por menor de flores, plantas, semillas, fertilizantes, animales de compañía y alimentos para los mismos en establecimientos especializados" },
                new Cnae { Key = "4777", CustomKey = "G4777", Name = "Comercio al por menor de artículos de relojería y joyería en establecimientos especializados" },
                new Cnae { Key = "4778", CustomKey = "G4778", Name = "Otro comercio al por menor de artículos nuevos en establecimientos especializados" },
                new Cnae { Key = "4779", CustomKey = "G4779", Name = "Comercio al por menor de artículos de segunda mano en establecimientos" },
                new Cnae { Key = "4781", CustomKey = "G4781", Name = "Comercio al por menor de productos alimenticios, bebidas y tabaco en puestos de venta y en mercadillos" },
                new Cnae { Key = "4782", CustomKey = "G4782", Name = "Comercio al por menor de productos textiles, prendas de vestir y calzado en puestos de venta y en mercadillos" },
                new Cnae { Key = "4789", CustomKey = "G4789", Name = "Comercio al por menor de otros productos en puestos de venta y en mercadillos" },
                new Cnae { Key = "4791", CustomKey = "G4791", Name = "Comercio al por menor por correspondencia o Internet" },
                new Cnae { Key = "4799", CustomKey = "G4799", Name = "Otro comercio al por menor no realizado ni en establecimientos, ni en puestos de venta ni en mercadillos" },
                new Cnae { Key = "4910", CustomKey = "H4910", Name = "Transporte interurbano de pasajeros por ferrocarril" },
                new Cnae { Key = "4920", CustomKey = "H4920", Name = "Transporte de mercancías por ferrocarril" },
                new Cnae { Key = "4931", CustomKey = "H4931", Name = "Transporte terrestre urbano y suburbano de pasajeros" },
                new Cnae { Key = "4932", CustomKey = "H4932", Name = "Transporte por taxi" },
                new Cnae { Key = "4939", CustomKey = "H4939", Name = "Otros tipos de transporte terrestre de pasajeros" },
                new Cnae { Key = "4941", CustomKey = "H4941", Name = "Transporte de mercancías por carretera" },
                new Cnae { Key = "4942", CustomKey = "H4942", Name = "Servicios de mudanza" },
                new Cnae { Key = "4950", CustomKey = "H4950", Name = "Transporte por tubería" },
                new Cnae { Key = "5010", CustomKey = "H5010", Name = "Transporte marítimo de pasajeros" },
                new Cnae { Key = "5020", CustomKey = "H5020", Name = "Transporte marítimo de mercancías" },
                new Cnae { Key = "5030", CustomKey = "H5030", Name = "Transporte de pasajeros por vías navegables interiores" },
                new Cnae { Key = "5040", CustomKey = "H5040", Name = "Transporte de mercancías por vías navegables interiores" },
                new Cnae { Key = "5110", CustomKey = "H5110", Name = "Transporte aéreo de pasajeros" },
                new Cnae { Key = "5121", CustomKey = "H5121", Name = "Transporte aéreo de mercancías" },
                new Cnae { Key = "5122", CustomKey = "H5122", Name = "Transporte espacial" },
                new Cnae { Key = "5210", CustomKey = "H5210", Name = "Depósito y almacenamiento" },
                new Cnae { Key = "5221", CustomKey = "H5221", Name = "Actividades anexas al transporte terrestre" },
                new Cnae { Key = "5222", CustomKey = "H5222", Name = "Actividades anexas al transporte marítimo y por vías navegables interiores" },
                new Cnae { Key = "5223", CustomKey = "H5223", Name = "Actividades anexas al transporte aéreo" },
                new Cnae { Key = "5224", CustomKey = "H5224", Name = "Manipulación de mercancías" },
                new Cnae { Key = "5229", CustomKey = "H5229", Name = "Otras actividades anexas al transporte" },
                new Cnae { Key = "5310", CustomKey = "H5310", Name = "Actividades postales sometidas a la obligación del servicio universal" },
                new Cnae { Key = "5320", CustomKey = "H5320", Name = "Otras actividades postales y de correos" },
                new Cnae { Key = "5510", CustomKey = "I5510", Name = "Hoteles y alojamientos similares" },
                new Cnae { Key = "5520", CustomKey = "I5520", Name = "Alojamientos turísticos y otros alojamientos de corta estancia" },
                new Cnae { Key = "5530", CustomKey = "I5530", Name = "Campings y aparcamientos para caravanas" },
                new Cnae { Key = "5590", CustomKey = "I5590", Name = "Otros alojamientos" },
                new Cnae { Key = "5610", CustomKey = "I5610", Name = "Restaurantes y puestos de comidas" },
                new Cnae { Key = "5621", CustomKey = "I5621", Name = "Provisión de comidas preparadas para eventos" },
                new Cnae { Key = "5629", CustomKey = "I5629", Name = "Otros servicios de comidas" },
                new Cnae { Key = "5630", CustomKey = "I5630", Name = "Establecimientos de bebidas" },
                new Cnae { Key = "5811", CustomKey = "J5811", Name = "Edición de libros" },
                new Cnae { Key = "5812", CustomKey = "J5812", Name = "Edición de directorios y guías de direcciones postales" },
                new Cnae { Key = "5813", CustomKey = "J5813", Name = "Edición de periódicos" },
                new Cnae { Key = "5814", CustomKey = "J5814", Name = "Edición de revistas" },
                new Cnae { Key = "5819", CustomKey = "J5819", Name = "Otras actividades editoriales" },
                new Cnae { Key = "5821", CustomKey = "J5821", Name = "Edición de videojuegos" },
                new Cnae { Key = "5829", CustomKey = "J5829", Name = "Edición de otros programas informáticos" },
                new Cnae { Key = "5912", CustomKey = "J5912", Name = "Actividades de postproducción cinematográfica, de vídeo y de programas de televisión" },
                new Cnae { Key = "5914", CustomKey = "J5914", Name = "Actividades de exhibición cinematográfica" },
                new Cnae { Key = "5915", CustomKey = "J5915", Name = "Actividades de producción cinematográfica y de vídeo" },
                new Cnae { Key = "5916", CustomKey = "J5916", Name = "Actividades de producciones de programas de televisión" },
                new Cnae { Key = "5917", CustomKey = "J5917", Name = "Actividades de distribución cinematográfica y de vídeo" },
                new Cnae { Key = "5918", CustomKey = "J5918", Name = "Actividades de distribución de programas de televisión" },
                new Cnae { Key = "5920", CustomKey = "J5920", Name = "Actividades de grabación de sonido y edición musical" },
                new Cnae { Key = "6010", CustomKey = "J6010", Name = "Actividades de radiodifusión" },
                new Cnae { Key = "6020", CustomKey = "J6020", Name = "Actividades de programación y emisión de televisión" },
                new Cnae { Key = "6110", CustomKey = "J6110", Name = "Telecomunicaciones por cable" },
                new Cnae { Key = "6120", CustomKey = "J6120", Name = "Telecomunicaciones inalámbricas" },
                new Cnae { Key = "6130", CustomKey = "J6130", Name = "Telecomunicaciones por satélite" },
                new Cnae { Key = "6190", CustomKey = "J6190", Name = "Otras actividades de telecomunicaciones" },
                new Cnae { Key = "6201", CustomKey = "J6201", Name = "Actividades de programación informática" },
                new Cnae { Key = "6202", CustomKey = "J6202", Name = "Actividades de consultoría informática" },
                new Cnae { Key = "6203", CustomKey = "J6203", Name = "Gestión de recursos informáticos" },
                new Cnae { Key = "6209", CustomKey = "J6209", Name = "Otros servicios relacionados con las tecnologías de la información y la informática" },
                new Cnae { Key = "6311", CustomKey = "J6311", Name = "Proceso de datos, hosting y actividades relacionadas" },
                new Cnae { Key = "6312", CustomKey = "J6312", Name = "Portales web" },
                new Cnae { Key = "6391", CustomKey = "J6391", Name = "Actividades de las agencias de noticias" },
                new Cnae { Key = "6399", CustomKey = "J6399", Name = "Otros servicios de información" },
                new Cnae { Key = "6411", CustomKey = "K6411", Name = "Banco central" },
                new Cnae { Key = "6419", CustomKey = "K6419", Name = "Otra intermediación monetaria" },
                new Cnae { Key = "6420", CustomKey = "K6420", Name = "Actividades de las sociedades holding" },
                new Cnae { Key = "6430", CustomKey = "K6430", Name = "Inversión colectiva, fondos y entidades financieras similares" },
                new Cnae { Key = "6491", CustomKey = "K6491", Name = "Arrendamiento financiero" },
                new Cnae { Key = "6492", CustomKey = "K6492", Name = "Otras actividades crediticias" },
                new Cnae { Key = "6499", CustomKey = "K6499", Name = "Otros servicios financieros, excepto seguros y fondos de pensiones" },
                new Cnae { Key = "6511", CustomKey = "K6511", Name = "Seguros de vida" },
                new Cnae { Key = "6512", CustomKey = "K6512", Name = "Seguros distintos de los seguros de vida" },
                new Cnae { Key = "6520", CustomKey = "K6520", Name = "Reaseguros" },
                new Cnae { Key = "6530", CustomKey = "K6530", Name = "Fondos de pensiones" },
                new Cnae { Key = "6611", CustomKey = "K6611", Name = "Administración de mercados financieros" },
                new Cnae { Key = "6612", CustomKey = "K6612", Name = "Actividades de intermediación en operaciones con valores y otros activos" },
                new Cnae { Key = "6619", CustomKey = "K6619", Name = "Otras actividades auxiliares a los servicios financieros, excepto seguros y fondos de pensiones" },
                new Cnae { Key = "6621", CustomKey = "K6621", Name = "Evaluación de riesgos y daños" },
                new Cnae { Key = "6622", CustomKey = "K6622", Name = "Actividades de agentes y corredores de seguros" },
                new Cnae { Key = "6629", CustomKey = "K6629", Name = "Otras actividades auxiliares a seguros y fondos de pensiones" },
                new Cnae { Key = "6630", CustomKey = "K6630", Name = "Actividades de gestión de fondos" },
                new Cnae { Key = "6810", CustomKey = "L6810", Name = "Compraventa de bienes inmobiliarios por cuenta propia" },
                new Cnae { Key = "6820", CustomKey = "L6820", Name = "Alquiler de bienes inmobiliarios por cuenta propia" },
                new Cnae { Key = "6831", CustomKey = "L6831", Name = "Agentes de la propiedad inmobiliaria" },
                new Cnae { Key = "6832", CustomKey = "L6832", Name = "Gestión y administración de la propiedad inmobiliaria" },
                new Cnae { Key = "6910", CustomKey = "M6910", Name = "Actividades jurídicas" },
                new Cnae { Key = "6920", CustomKey = "M6920", Name = "Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal" },
                new Cnae { Key = "7010", CustomKey = "M7010", Name = "Actividades de las sedes centrales" },
                new Cnae { Key = "7021", CustomKey = "M7021", Name = "Relaciones públicas y comunicación" },
                new Cnae { Key = "7022", CustomKey = "M7022", Name = "Otras actividades de consultoría de gestión empresarial" },
                new Cnae { Key = "7111", CustomKey = "M7111", Name = "Servicios técnicos de arquitectura" },
                new Cnae { Key = "7112", CustomKey = "M7112", Name = "Servicios técnicos de ingeniería y otras actividades relacionadas con el asesoramiento técnico" },
                new Cnae { Key = "7120", CustomKey = "M7120", Name = "Ensayos y análisis técnicos" },
                new Cnae { Key = "7211", CustomKey = "M7211", Name = "Investigación y desarrollo experimental en biotecnología" },
                new Cnae { Key = "7219", CustomKey = "M7219", Name = "Otra investigación y desarrollo experimental en ciencias naturales y técnicas" },
                new Cnae { Key = "7220", CustomKey = "M7220", Name = "Investigación y desarrollo experimental en ciencias sociales y humanidades" },
                new Cnae { Key = "7311", CustomKey = "M7311", Name = "Agencias de publicidad" },
                new Cnae { Key = "7312", CustomKey = "M7312", Name = "Servicios de representación de medios de comunicación" },
                new Cnae { Key = "7320", CustomKey = "M7320", Name = "Estudio de mercado y realización de encuestas de opinión pública" },
                new Cnae { Key = "7410", CustomKey = "M7410", Name = "Actividades de diseño especializado" },
                new Cnae { Key = "7420", CustomKey = "M7420", Name = "Actividades de fotografía" },
                new Cnae { Key = "7430", CustomKey = "M7430", Name = "Actividades de traducción e interpretación" },
                new Cnae { Key = "7490", CustomKey = "M7490", Name = "Otras actividades profesionales, científicas y técnicas" },
                new Cnae { Key = "7500", CustomKey = "M7500", Name = "Actividades veterinarias" },
                new Cnae { Key = "7711", CustomKey = "N7711", Name = "Alquiler de automóviles y vehículos de motor ligeros" },
                new Cnae { Key = "7712", CustomKey = "N7712", Name = "Alquiler de camiones" },
                new Cnae { Key = "7721", CustomKey = "N7721", Name = "Alquiler de artículos de ocio y deportivos" },
                new Cnae { Key = "7722", CustomKey = "N7722", Name = "Alquiler de cintas de vídeo y discos" },
                new Cnae { Key = "7729", CustomKey = "N7729", Name = "Alquiler de otros efectos personales y artículos de uso doméstico" },
                new Cnae { Key = "7731", CustomKey = "N7731", Name = "Alquiler de maquinaria y equipo de uso agrícola" },
                new Cnae { Key = "7732", CustomKey = "N7732", Name = "Alquiler de maquinaria y equipo para la construcción e ingeniería civil" },
                new Cnae { Key = "7733", CustomKey = "N7733", Name = "Alquiler de maquinaria y equipo de oficina, incluidos ordenadores" },
                new Cnae { Key = "7734", CustomKey = "N7734", Name = "Alquiler de medios de navegación" },
                new Cnae { Key = "7735", CustomKey = "N7735", Name = "Alquiler de medios de transporte aéreo" },
                new Cnae { Key = "7739", CustomKey = "N7739", Name = "Alquiler de otra maquinaria, equipos y bienes tangibles" },
                new Cnae { Key = "7740", CustomKey = "N7740", Name = "Arrendamiento de la propiedad intelectual y productos similares, excepto trabajos protegidos por los derechos de autor" },
                new Cnae { Key = "7810", CustomKey = "N7810", Name = "Actividades de las agencias de colocación" },
                new Cnae { Key = "7820", CustomKey = "N7820", Name = "Actividades de las empresas de trabajo temporal" },
                new Cnae { Key = "7830", CustomKey = "N7830", Name = "Otra provisión de recursos humanos" },
                new Cnae { Key = "7911", CustomKey = "N7911", Name = "Actividades de las agencias de viajes" },
                new Cnae { Key = "7912", CustomKey = "N7912", Name = "Actividades de los operadores turísticos" },
                new Cnae { Key = "7990", CustomKey = "N7990", Name = "Otros servicios de reservas y actividades relacionadas con los mismos" },
                new Cnae { Key = "8010", CustomKey = "N8010", Name = "Actividades de seguridad privada" },
                new Cnae { Key = "8020", CustomKey = "N8020", Name = "Servicios de sistemas de seguridad" },
                new Cnae { Key = "8030", CustomKey = "N8030", Name = "Actividades de investigación" },
                new Cnae { Key = "8110", CustomKey = "N8110", Name = "Servicios integrales a edificios e instalaciones" },
                new Cnae { Key = "8121", CustomKey = "N8121", Name = "Limpieza general de edificios" },
                new Cnae { Key = "8122", CustomKey = "N8122", Name = "Otras actividades de limpieza industrial y de edificios" },
                new Cnae { Key = "8129", CustomKey = "N8129", Name = "Otras actividades de limpieza" },
                new Cnae { Key = "8130", CustomKey = "N8130", Name = "Actividades de jardinería" },
                new Cnae { Key = "8211", CustomKey = "N8211", Name = "Servicios administrativos combinados" },
                new Cnae { Key = "8219", CustomKey = "N8219", Name = "Actividades de fotocopiado, preparación de documentos y otras actividades especializadas de oficina" },
                new Cnae { Key = "8220", CustomKey = "N8220", Name = "Actividades de los centros de llamadas" },
                new Cnae { Key = "8230", CustomKey = "N8230", Name = "Organización de convenciones y ferias de muestras" },
                new Cnae { Key = "8291", CustomKey = "N8291", Name = "Actividades de las agencias de cobros y de información comercial" },
                new Cnae { Key = "8292", CustomKey = "N8292", Name = "Actividades de envasado y empaquetado" },
                new Cnae { Key = "8299", CustomKey = "N8299", Name = "Otras actividades de apoyo a las empresas" },
                new Cnae { Key = "8411", CustomKey = "O8411", Name = "Actividades generales de la Administración Pública" },
                new Cnae { Key = "8412", CustomKey = "O8412", Name = "Regulación de las actividades sanitarias, educativas y culturales y otros servicios sociales, excepto Seguridad Social" },
                new Cnae { Key = "8413", CustomKey = "O8413", Name = "Regulación de la actividad económica y contribución a su mayor eficiencia" },
                new Cnae { Key = "8421", CustomKey = "O8421", Name = "Asuntos exteriores" },
                new Cnae { Key = "8422", CustomKey = "O8422", Name = "Defensa" },
                new Cnae { Key = "8423", CustomKey = "O8423", Name = "Justicia" },
                new Cnae { Key = "8424", CustomKey = "O8424", Name = "Orden público y seguridad" },
                new Cnae { Key = "8425", CustomKey = "O8425", Name = "Protección civil" },
                new Cnae { Key = "8430", CustomKey = "O8430", Name = "Seguridad Social obligatoria" },
                new Cnae { Key = "8510", CustomKey = "P8510", Name = "Educación preprimaria" },
                new Cnae { Key = "8520", CustomKey = "P8520", Name = "Educación primaria" },
                new Cnae { Key = "8531", CustomKey = "P8531", Name = "Educación secundaria general" },
                new Cnae { Key = "8532", CustomKey = "P8532", Name = "Educación secundaria técnica y profesional" },
                new Cnae { Key = "8541", CustomKey = "P8541", Name = "Educación postsecundaria no terciaria" },
                new Cnae { Key = "8543", CustomKey = "P8543", Name = "Educación universitaria" },
                new Cnae { Key = "8544", CustomKey = "P8544", Name = "Educación terciaria no universitaria" },
                new Cnae { Key = "8551", CustomKey = "P8551", Name = "Educación deportiva y recreativa" },
                new Cnae { Key = "8552", CustomKey = "P8552", Name = "Educación cultural" },
                new Cnae { Key = "8553", CustomKey = "P8553", Name = "Actividades de las escuelas de conducción y pilotaje" },
                new Cnae { Key = "8559", CustomKey = "P8559", Name = "Otra educación" },
                new Cnae { Key = "8560", CustomKey = "P8560", Name = "Actividades auxiliares a la educación" },
                new Cnae { Key = "8610", CustomKey = "Q8610", Name = "Actividades hospitalarias" },
                new Cnae { Key = "8621", CustomKey = "Q8621", Name = "Actividades de medicina general" },
                new Cnae { Key = "8622", CustomKey = "Q8622", Name = "Actividades de medicina especializada" },
                new Cnae { Key = "8623", CustomKey = "Q8623", Name = "Actividades odontológicas" },
                new Cnae { Key = "8690", CustomKey = "Q8690", Name = "Otras actividades sanitarias" },
                new Cnae { Key = "8710", CustomKey = "Q8710", Name = "Asistencia en establecimientos residenciales con cuidados sanitarios" },
                new Cnae { Key = "8720", CustomKey = "Q8720", Name = "Asistencia en establecimientos residenciales para personas con discapacidad intelectual, enfermedad mental y drogodependencia" },
                new Cnae { Key = "8731", CustomKey = "Q8731", Name = "Asistencia en establecimientos residenciales para personas mayores" },
                new Cnae { Key = "8732", CustomKey = "Q8732", Name = "Asistencia en establecimientos residenciales para personas con discapacidad física" },
                new Cnae { Key = "8790", CustomKey = "Q8790", Name = "Otras actividades de asistencia en establecimientos residenciales" },
                new Cnae { Key = "8811", CustomKey = "Q8811", Name = "Actividades de servicios sociales sin alojamiento para personas mayores" },
                new Cnae { Key = "8812", CustomKey = "Q8812", Name = "Actividades de servicios sociales sin alojamiento para personas con discapacidad" },
                new Cnae { Key = "8891", CustomKey = "Q8891", Name = "Actividades de cuidado diurno de niños" },
                new Cnae { Key = "8899", CustomKey = "Q8899", Name = "Otros actividades de servicios sociales sin alojamiento" },
                new Cnae { Key = "9001", CustomKey = "R9001", Name = "Artes escénicas" },
                new Cnae { Key = "9002", CustomKey = "R9002", Name = "Actividades auxiliares a las artes escénicas" },
                new Cnae { Key = "9003", CustomKey = "R9003", Name = "Creación artística y literaria" },
                new Cnae { Key = "9004", CustomKey = "R9004", Name = "Gestión de salas de espectáculos" },
                new Cnae { Key = "9102", CustomKey = "R9102", Name = "Actividades de museos" },
                new Cnae { Key = "9103", CustomKey = "R9103", Name = "Gestión de lugares y edificios históricos" },
                new Cnae { Key = "9104", CustomKey = "R9104", Name = "Actividades de los jardines botánicos, parques zoológicos y reservas naturales" },
                new Cnae { Key = "9105", CustomKey = "R9105", Name = "Actividades de bibliotecas" },
                new Cnae { Key = "9106", CustomKey = "R9106", Name = "Actividades de archivos" },
                new Cnae { Key = "9200", CustomKey = "R9200", Name = "Actividades de juegos de azar y apuestas" },
                new Cnae { Key = "9311", CustomKey = "R9311", Name = "Gestión de instalaciones deportivas" },
                new Cnae { Key = "9312", CustomKey = "R9312", Name = "Actividades de los clubes deportivos" },
                new Cnae { Key = "9313", CustomKey = "R9313", Name = "Actividades de los gimnasios" },
                new Cnae { Key = "9319", CustomKey = "R9319", Name = "Otras actividades deportivas" },
                new Cnae { Key = "9321", CustomKey = "R9321", Name = "Actividades de los parques de atracciones y los parques temáticos" },
                new Cnae { Key = "9329", CustomKey = "R9329", Name = "Otras actividades recreativas y de entretenimiento" },
                new Cnae { Key = "9411", CustomKey = "S9411", Name = "Actividades de organizaciones empresariales y patronales" },
                new Cnae { Key = "9412", CustomKey = "S9412", Name = "Actividades de organizaciones profesionales" },
                new Cnae { Key = "9420", CustomKey = "S9420", Name = "Actividades sindicales" },
                new Cnae { Key = "9491", CustomKey = "S9491", Name = "Actividades de organizaciones religiosas" },
                new Cnae { Key = "9492", CustomKey = "S9492", Name = "Actividades de organizaciones políticas" },
                new Cnae { Key = "9499", CustomKey = "S9499", Name = "Otras actividades asociativas" },
                new Cnae { Key = "9511", CustomKey = "S9511", Name = "Reparación de ordenadores y equipos periféricos" },
                new Cnae { Key = "9512", CustomKey = "S9512", Name = "Reparación de equipos de comunicación" },
                new Cnae { Key = "9521", CustomKey = "S9521", Name = "Reparación de aparatos electrónicos de audio y vídeo de uso doméstico" },
                new Cnae { Key = "9522", CustomKey = "S9522", Name = "Reparación de aparatos electrodomésticos y de equipos para el hogar y el jardín" },
                new Cnae { Key = "9523", CustomKey = "S9523", Name = "Reparación de calzado y artículos de cuero" },
                new Cnae { Key = "9524", CustomKey = "S9524", Name = "Reparación de muebles y artículos de menaje" },
                new Cnae { Key = "9525", CustomKey = "S9525", Name = "Reparación de relojes y joyería" },
                new Cnae { Key = "9529", CustomKey = "S9529", Name = "Reparación de otros efectos personales y artículos de uso doméstico" },
                new Cnae { Key = "9601", CustomKey = "S9601", Name = "Lavado y limpieza de prendas textiles y de piel" },
                new Cnae { Key = "9602", CustomKey = "S9602", Name = "Peluquería y otros tratamientos de belleza" },
                new Cnae { Key = "9603", CustomKey = "S9603", Name = "Pompas fúnebres y actividades relacionadas" },
                new Cnae { Key = "9604", CustomKey = "S9604", Name = "Actividades de mantenimiento físico" },
                new Cnae { Key = "9609", CustomKey = "S9609", Name = "Otras servicios personales" },
                new Cnae { Key = "9700", CustomKey = "T9700", Name = "Actividades de los hogares como empleadores de personal doméstico" },
                new Cnae { Key = "9810", CustomKey = "T9810", Name = "Actividades de los hogares como productores de bienes para uso propio" },
                new Cnae { Key = "9820", CustomKey = "T9820", Name = "Actividades de los hogares como productores de servicios para uso propio" }
            };

            return cnaes;
        }
    }
}
